- name: Seguro de Vida
  description: Para cuidar a tu familia cuando no estés.
  image: assets/images/services/seguro de vida.jpg
  benefits: reemplazo de ingresos, pago de deudas, educación de hijos.
  best_for: padres/madres, personas con dependientes, emprendedores con créditos.
  companies:
  - BMI
  - American Fidelity
  - Olé
- name: Retiro / Jubilación
  description: Un día vas a dejar de trabajar, tus ingresos no tienen por qué detenerse.
  image: assets/images/services/retiro.jpg
  benefits: ahorro con interés compuesto, disciplina automática, opciones de rescate. 
  best_for: 25–55 años que quieren complementar su jubilación.
  companies:
  - BMI
  - Investor Trust
- name: Seguro Educativo (Ahorro para hijos)
  description: Convertí tu amor en oportunidades reales.
  image: assets/images/services/seguro educativo.jpg
  benefits: fondo para universidad/colegio, metas por etapas, tranquilidad financiera.
  best_for: familias con niños desde 0 a 15 años.
  companies:
  - BMI
  - Investor Trust
- name: Salud y Gastos Médicos
  description: Para que una urgencia no comprometa tus finanzas.
  image: assets/images/services/seguro de salud.jpg
  benefits: cobertura hospitalaria, especialistas, estudios, red médica.
  best_for: familias, trabajadores independientes y empresas.
  companies:
  - BMI
  - Morgan White
  - Ever
- name: Ahorro e Inversión
  description: Hacé crecer tu dinero mientras vivís la vida.
  image: assets/images/services/inversiones.jpg
  benefits: interés compuesto, metas (viajes, casa, fondo de emergencia).
  best_for: quienes buscan ordenar finanzas y crecer con propósito.
  companies:
  - Investor Trust
- name: Seguro Viajero
  description: Protegé tu viaje desde el primer día, estés donde estés.
  image: assets/images/services/seguro viajero.jpg
  benefits: Cobertura médica internacional. / Asistencia en casos de pérdida de equipaje o retrasos. / Apoyo 24/7 durante tu viaje.
  best_for: personas que viajan por trabajo, estudios o vacaciones.
  companies:
  - BMI
- name: Seguro de Incapacidad
  description: Si no podés trabajar, tus ingresos no deberían detenerse.
  image: assets/images/services/incapacidad.jpg
  benefits: Reemplazo parcial o total de ingresos en caso de accidente o enfermedad. / Protección de estilo de vida y compromisos financieros / Planes adaptados según tu ocupación y nivel de riesgo.
  best_for: trabajadores independientes, profesionales y cabezas de familia.
  companies:
  - Morgan White
